# Generated by Django 5.0.6 on 2024-06-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_alter_generaldata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldata',
            name='unique_id',
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
