# Generated by Django 5.0.6 on 2024-06-12 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0003_generaldata_unique_id_alter_generaldata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='Un-available', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='generaldata',
            name='imagelink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authz.imagelink'),
        ),
    ]
