# Generated by Django 5.0.6 on 2024-06-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0004_imagelink_generaldata_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldata',
            name='imagelink',
            field=models.CharField(default='un-available', max_length=255),
        ),
        migrations.DeleteModel(
            name='ImageLink',
        ),
    ]
