# Generated by Django 5.0.6 on 2024-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0005_alter_generaldata_imagelink_delete_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldata',
            name='imagelink',
            field=models.CharField(default='un-available', max_length=255, null=True),
        ),
    ]
