# Generated by Django 5.0.6 on 2024-06-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0006_alter_generaldata_imagelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
            ],
        ),
    ]
